build:
  command: npm run build
  commandOrigin: config
  publish: /opt/build/repo/out
  publishOrigin: config
plugins:
  - inputs:
      skip: true
    origin: config
    package: "@netlify/plugin-nextjs"
    
